server:
  port: 1050 # 端口号

eureka:
  client: # Eureka客户端配置，指向注册中心地址
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/
    registery-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true # 开启使用IP地址进行注册
    instance-id: zuul-server:1050 # 修改实例Id

spring:
  application: # 指定此服务的应用名称
    name: zuul-server

zuul:
  prefix: "/servers"  #统一访问前缀
  ignoredServices: "*"  #禁用掉使用浏览器通过服务名的方式访问服务
  routes:
    pay-server: "/pay/**"   #指定pay-server这个服务使用 /pay路径来访问  - 别名
    order-server: "/order/**"   #指定order-server这个服务使用 /order路径来访问
    user-server: "/user/**"