server:
  port: 1020 # user服务端口号

eureka:
  client:
    serviceUrl: # Eureka客户端配置，指向注册中心地址
      defaultZone: http://localhost:1010/eureka/
    registery-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true # 开启使用IP地址进行注册
    instance-id: user-server:1020 # 修改实例Id

spring:
  application: # 指定此服务的应用名称
    name: user-server
  profiles:
    active: user-server1
---
server:
  port: 1020
eureka:
  instance:
    instance-id: user-server:1020
spring:
  profiles: user-server1
---
server:
  port: 1021
eureka:
  instance:
    instance-id: user-server:1021
spring:
  profiles: user-server2


